"""
Markdown report generator with Windows-compatible file links.
"""

from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime
import urllib.parse

from src.core.logger import get_logger


logger = get_logger(__name__)


class MarkdownReportGenerator:
    """
    Generate professional Markdown reports from search results.
    Includes clickable file links compatible with Windows 11.
    """
    
    def __init__(self):
        pass
    
    def generate(
        self,
        results: List[Dict[str, Any]],
        query: str,
        output_path: Path
    ) -> bool:
        """
        Generate Markdown report from search results.
        
        Args:
            results: List of search result dictionaries
            query: Original search query
            output_path: Where to save the report
        
        Returns:
            True if report was generated successfully
        """
        try:
            logger.info(f"Generating Markdown report at {output_path}")
            
            # Build report content
            lines = []
            
            # Header
            lines.append(f"# Search Report: \"{query}\"")
            lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | **Found:** {len(results)} Files")
            lines.append("")
            lines.append("---")
            lines.append("")
            
            # Results
            if not results:
                lines.append("*No files found matching the criteria.*")
            else:
                for idx, result in enumerate(results, 1):
                    lines.extend(self._format_result(idx, result))
                    lines.append("")
            
            # Footer
            lines.append("---")
            lines.append("")
            lines.append("*Generated by OmniSearch Pro*")
            
            # Write to file
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write("\n".join(lines))
            
            logger.info(f"Report generated: {len(results)} results")
            return True
        
        except Exception as e:
            logger.error(f"Error generating report: {e}", exc_info=True)
            return False
    
    def _format_result(self, index: int, result: Dict[str, Any]) -> List[str]:
        """Format a single search result for Markdown."""
        lines = []
        
        # Construct full path
        full_path = str(Path(result['parent_path']) / result['filename'])
        
        # Title with filename
        lines.append(f"### {index}. {result['filename']}")
        
        # Metadata
        size = self._format_size(result.get('size_bytes', 0))
        modified = self._format_timestamp(result.get('modified_at', 0))
        lines.append(f"* **Path:** `{result['parent_path']}`")
        lines.append(f"* **Size:** {size} | **Modified:** {modified}")
        
        # Content snippet if available
        if result.get('snippet'):
            snippet = result['snippet'].replace('<mark>', '**').replace('</mark>', '**')
            lines.append(f"* **Preview:**")
            lines.append(f"  > {snippet}")
        
        # Links
        file_link = self._make_windows_link(full_path, "Open File")
        folder_link = self._make_windows_link(result['parent_path'], "Open Folder")
        lines.append(f"* {file_link} | {folder_link}")
        
        lines.append("")
        lines.append("---")
        
        return lines
    
    def _make_windows_link(self, filepath: str, label: str) -> str:
        """
        Create Windows-compatible file:/// link for Markdown.
        
        Args:
            filepath: Windows path (C:\\Users\\...)
            label: Link text
        
        Returns:
            Markdown link string
        """
        # Convert to Path and get URI
        path = Path(filepath).resolve()
        uri = path.as_uri()
        
        return f"[{label}]({uri})"
    
    def _format_size(self, size_bytes: int) -> str:
        """Format byte size to human-readable string."""
        for unit in ['B', 'KB', 'MB', 'GB']:
            if size_bytes < 1024.0:
                return f"{size_bytes:.1f} {unit}"
            size_bytes /= 1024.0
        return f"{size_bytes:.1f} TB"
    
    def _format_timestamp(self, timestamp: int) -> str:
        """Format Unix timestamp to readable date."""
        try:
            dt = datetime.fromtimestamp(timestamp)
            return dt.strftime("%Y-%m-%d")
        except:
            return "Unknown"